### PR TITLE
fixed creation of notifyOK and NotifyErr functions in processor

### LINKED ISSUE #41: stream number incorrectly passed to NotifyOK and NotifyErr functions
When [creating](https://github.com/stoewer/go-nakadi/blob/master/processor.go#L126) stream options stream index is not properly passed to notify functions. Closure should be created here for the index:
```
for i := uint(0); i < options.StreamCount; i++ {
   ...
   CommitMaxElapsedTime: options.CommitMaxElapsedTime,
	NotifyErr:            func(err error, duration time.Duration) { options.NotifyErr(i, err, duration) },
	NotifyOK:             func() { options.NotifyOK(i) }}
...
```

### PR DESCRIPTION
**Pull request by krnkl**
fixed creation of notifyOK and NotifyErr functions in processor
this fixes #41

### CODE REVIEW

File: processor.go [hunk 1]
```diff
@@ -122,9 +122,13 @@ func NewProcessor(client *Client, subscriptionID string, options *ProcessorOptio
 			InitialRetryInterval: options.InitialRetryInterval,
 			MaxRetryInterval:     options.MaxRetryInterval,
 			CommitMaxElapsedTime: options.CommitMaxElapsedTime,
-			NotifyErr:            func(err error, duration time.Duration) { options.NotifyErr(i, err, duration) },
-			NotifyOK:             func() { options.NotifyOK(i) }}
-
+			NotifyErr: func(streamNo uint) func(err error, duration time.Duration) {
```
Comment (stoewer) [inline processor.go]: `minor` you can achieve capture of the value in the closure just by assigning `i` to a local variable `streamNo` inside of the loop:
```go
for i := uint(0); i < options.StreamCount; i++ {
	streamNo := i
	streamOptions := StreamOptions{
		BatchLimit:           options.BatchLimit,
		FlushTimeout:         options.FlushTimeout,
		MaxUncommittedEvents: options.MaxUncommittedEvents,
		InitialRetryInterval: options.InitialRetryInterval,
		MaxRetryInterval:     options.MaxRetryInterval,
		CommitMaxElapsedTime: options.CommitMaxElapsedTime,
		NotifyErr: func(err error, duration time.Duration) { options.NotifyErr(streamNo, err, duration) },
		NotifyOK: func() { options.NotifyOK(streamNo) },
	}
	processor.streamOptions = append(processor.streamOptions, streamOptions)
}
```
Unless I'm missing something here, I think I prefer the version using the local variable in this case. What do you think?

Comment (krnkl) [reply processor.go]: fixed
